# .scrutinizer.yml
build:
    environment:
        php:
            version: 8.1
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --bootstrap test/bootstrap.php -c test/phpunit.xml.dist'
                coverage:
                    file: 'tmp/coverage-clover.xml'
                    format: 'clover'
