# Simple enough
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # MG No testing on 5.6, because it's such a pain as our PHPUnit supports 7.0 minimum.
  # aliased to a recent 5.6.x version
  #- 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent 7.1 version
  - 7.1
#  # aliased to a recent hhvm version
#  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
#env:
#  - DB=mysql
#  - DB=pgsql

# optionally set up exclutions and allowed failures in the matrix
matrix:
#  exclude:
#    - php: hhvm
#      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
#  allow_failures:
#    - php: 7.0
#    - php: hhvm

install:
  - composer install --no-interaction

# execute any number of scripts before the test run, custom env's are available as variables
#before_script:
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration test/phpunit.xml.dist --coverage-text --bootstrap test/bootstrap.php

# configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#yourfavouriteroomfortravis"
